### ISSUE TITLE
could not run on an android device，some thing wrong when class verifing

### ISSUE THREAD

**Issue by jeyhan** [SQiShER/java-object-diff#170]
```
09-13 18:39:24.950 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
09-13 18:39:24.950 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onSearchRequested
09-13 18:39:24.950 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve interface method 14479: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
09-13 18:39:24.950 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
09-13 18:39:24.950 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onWindowStartingActionMode
09-13 18:39:24.950 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve interface method 14483: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
09-13 18:39:24.950 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
09-13 18:39:25.010 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
09-13 18:39:25.010 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve virtual method 406: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
09-13 18:39:25.010 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
09-13 18:39:25.010 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
09-13 18:39:25.010 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve virtual method 428: Landroid/content/res/TypedArray;.getType (I)I
09-13 18:39:25.010 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
09-13 18:39:25.070 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method org.slf4j.impl.StaticLoggerBinder.getSingleton, referenced from method org.slf4j.LoggerFactory.bind
09-13 18:39:25.070 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve static method 17667: Lorg/slf4j/impl/StaticLoggerBinder;.getSingleton ()Lorg/slf4j/impl/StaticLoggerBinder;
09-13 18:39:25.070 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x71 at 0x000e
09-13 18:39:25.070 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method org.slf4j.impl.StaticLoggerBinder.getSingleton, referenced from method org.slf4j.LoggerFactory.getILoggerFactory
09-13 18:39:25.070 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve static method 17667: Lorg/slf4j/impl/StaticLoggerBinder;.getSingleton ()Lorg/slf4j/impl/StaticLoggerBinder;
09-13 18:39:25.070 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x71 at 0x0022
09-13 18:39:25.080 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method org.slf4j.impl.StaticLoggerBinder.getSingleton, referenced from method org.slf4j.LoggerFactory.reportActualBinding
09-13 18:39:25.080 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve static method 17667: Lorg/slf4j/impl/StaticLoggerBinder;.getSingleton ()Lorg/slf4j/impl/StaticLoggerBinder;
09-13 18:39:25.080 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x71 at 0x0013
09-13 18:39:25.080 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve static field 6013 (REQUESTED_API_VERSION) in Lorg/slf4j/impl/StaticLoggerBinder;
09-13 18:39:25.080 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x62 at 0x0000
09-13 18:39:25.080 8104-8104/uc.com.testdiff W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
09-13 18:39:25.080 8104-8104/uc.com.testdiff W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
09-13 18:39:25.080 8104-8104/uc.com.testdiff W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/beans/BeanInfo;)
09-13 18:39:25.090 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method java.beans.BeanInfo.getPropertyDescriptors, referenced from method de.danielbechler.diff.introspection.StandardIntrospector.internalIntrospect
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve interface method 16653: Ljava/beans/BeanInfo;.getPropertyDescriptors ()[Ljava/beans/PropertyDescriptor;
09-13 18:39:25.090 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x72 at 0x0009
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/beans/PropertyDescriptor;)
09-13 18:39:25.090 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method java.beans.PropertyDescriptor.getName, referenced from method de.danielbechler.diff.introspection.StandardIntrospector.shouldSkip
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve virtual method 16655: Ljava/beans/PropertyDescriptor;.getName ()Ljava/lang/String;
09-13 18:39:25.090 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x6e at 0x0001
09-13 18:39:25.090 8104-8104/uc.com.testdiff I/dalvikvm: Could not find method java.beans.Introspector.getBeanInfo, referenced from method de.danielbechler.diff.introspection.StandardIntrospector.getBeanInfo
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve static method 16654: Ljava/beans/Introspector;.getBeanInfo (Ljava/lang/Class;)Ljava/beans/BeanInfo;
09-13 18:39:25.090 8104-8104/uc.com.testdiff D/dalvikvm: VFY: replacing opcode 0x71 at 0x0000
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to resolve exception class 2049 (Ljava/beans/IntrospectionException;)
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY: unable to find exception handler at addr 0xa
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY:  rejected Lde/danielbechler/diff/introspection/StandardIntrospector;.introspect (Ljava/lang/Class;)Lde/danielbechler/diff/instantiation/TypeInfo;
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY:  rejecting opcode 0x0d at 0x000a
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: VFY:  rejected Lde/danielbechler/diff/introspection/StandardIntrospector;.introspect (Ljava/lang/Class;)Lde/danielbechler/diff/instantiation/TypeInfo;
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: Verifier rejected class Lde/danielbechler/diff/introspection/StandardIntrospector;
09-13 18:39:25.090 8104-8104/uc.com.testdiff D/AndroidRuntime: Shutting down VM
09-13 18:39:25.090 8104-8104/uc.com.testdiff W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4180d8c8)
09-13 18:39:25.100 8104-8104/uc.com.testdiff E/AndroidRuntime: FATAL EXCEPTION: main
                                                               java.lang.VerifyError: de/danielbechler/diff/introspection/StandardIntrospector
                                                                   at de.danielbechler.diff.introspection.IntrospectionService.introspectorForNode(IntrospectionService.java:111)
                                                                   at de.danielbechler.diff.introspection.IntrospectionService.typeInfoForNode(IntrospectionService.java:89)
                                                                   at de.danielbechler.diff.differ.BeanDiffer.compareUsingIntrospection(BeanDiffer.java:110)
                                                                   at de.danielbechler.diff.differ.BeanDiffer.compareUsingAppropriateMethod(BeanDiffer.java:104)
                                                                   at de.danielbechler.diff.differ.BeanDiffer.compare(BeanDiffer.java:90)
                                                                   at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:202)
                                                                   at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:172)
                                                                   at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:159)
                                                                   at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:105)
                                                                   at de.danielbechler.diff.ObjectDiffer.compare(ObjectDiffer.java:52)
                                                                   at uc.com.testdiff.diff.TestDiffClass.test(TestDiffClass.java:28)
                                                                   at uc.com.testdiff.MainActivity.onCreate(MainActivity.java:14)
                                                                   at android.app.Activity.performCreate(Activity.java:5372)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
```

**Comment by SQiShER** [comment]
I've never done any Android development, so all I'm saying now is solely based on the things I learned from reported issues like this. As far as I know, people have been able to use the library on Android. However, I think they had to write their own custom introspector, because the Android VM doesn't come with the classes of package `java.beans` (like `BeanInfo`, `PropertyDescriptor` and `IntrospectionException`). The `StandardIntrospector` uses these classes to gather all the relevant information about the given object types.

Those `VerifyErrors` you are seeing seem to be [a common problem for Android developers](http://stackoverflow.com/questions/668788/android-java-lang-verifyerror). Unfortunately I can't really help you with those, due to my lack of knowledge in that regard. I recommend looking into them before trying to fix anything specific to java-object-diff, because some of the errors in your log are  looking to me like there is a bigger problem going on.

Once we can rule out anything Android-related we can start looking into the `StandardIntrospector` issue. Maybe it makes sense to provide an alternate Introspector which is solely based on reflection.

**Comment by jeyhan** [comment]
exactly words, I just tried copy java.beans package to src dir, which approved your theory.
I think really maybe make sence that implement a Introspector just base on reflection, just consider some  dvm/art and versions adaptation issues..
hope there will be an android version soon^^

**Comment by SQiShER** [comment]
If you like to give it a shot, feel free to submit a Pull Request with an Android-friendly Introspector. 😉

**Comment by jeyhan** [comment]
I will have a try :wink::wink:
